import { Paper } from './types';

export const MOCK_PAPERS: Paper[] = [
    {
        id: '1',
        title: 'Investigation of Random Laser in the Machine Learning Approach',
        authors: 'E. Santos',
        date: 'Nov. 2023',
        abstract: 'Machine Learning and Deep Learning are computational tools that fall within the domain of artificial intelligence. In recent years, numerous research works have advanced the application of machine and deep learning in various fields, including optics and photonics. In this...',
        categories: ['physics.optics'],
        url: 'https://arxiv.org/abs/2311.18579',
        source: 'research',
    },
    {
        id: '2',
        title: 'Machine Learning-enhanced Efficient Spectroscopic Ellipsometry Modeling',
        authors: 'A. Arunachalam',
        date: 'Jan. 2022',
        abstract: 'Over the recent years, there has been an extensive adoption of Machine Learning (ML) in a plethora of real-world applications, ranging from computer vision to data mining and drug discovery. In this paper, we utilize ML to facilitate efficient film fabrication, specifically...',
        categories: ['cond-mat.mtrl-sci', 'cs.LG'],
        url: 'https://arxiv.org/abs/2201.12061',
        source: 'research',
    },
    {
        id: '3',
        title: 'Machine Learning Regression of extinction in the second Gaia Data Release',
        authors: 'Y. Bai',
        date: 'Dec. 2019',
        abstract: 'Machine learning has become a popular tool to help us make better decisions and predictions, based on experiences, observations and analysing patterns within a given data set without explicitly functions. In this paper, we describe an application of the supervised...',
        categories: ['astro-ph.EP', 'astro-ph.SR'],
        url: 'https://arxiv.org/abs/1912.04987',
        source: 'research',
    },
    {
        id: '4',
        title: 'Artificial Intelligence and Machine Learning to Predict and Improve Efficiency in Organizations',
        authors: 'H. Chen',
        date: 'Sep. 2021',
        abstract: 'The use of artificial intelligence and machine learning is becoming increasingly prevalent in modern society. This paper explores the application of these technologies to predict and enhance operational efficiency within large-scale organizations, focusing on resource allocation...',
        categories: ['cs.AI', 'cs.LG'],
        url: 'https://arxiv.org',
        source: 'patent',
    },
    {
        id: '5',
        title: 'Beyond optimization -- supervised learning applications in relativistic laser-plasma interactions',
        authors: 'M. Kasim',
        date: 'Apr. 2020',
        abstract: 'Supervised machine learning is a powerful tool for finding complex, non-linear relationships in data. This capability has led to its application in a wide array of scientific fields. Here, we demonstrate its utility in the context of high-intensity laser-plasma physics by...',
        categories: ['physics.plasm-ph', 'cs.LG'],
        url: 'https://arxiv.org',
        source: 'research',
    },
    {
        id: '6',
        title: 'Beam Detection Based on Machine Learning Algorithms',
        authors: 'U. Jamil',
        date: 'Jan. 2023',
        abstract: 'This research paper investigates the use of various machine learning algorithms for beam detection in particle accelerators. We compare the performance of Support Vector Machines (SVM), Neural Networks, and Gradient Boosting on simulated and experimental data. Our results...',
        categories: ['physics.ins-det', 'cs.LG'],
        url: 'https://arxiv.org',
        source: 'patent',
    },
    {
        id: '7',
        title: 'A Novel Quantum-Resistant Cryptographic Algorithm',
        authors: 'L. Valerius, S. Chen',
        date: 'Jul. 2023',
        abstract: 'With the advent of quantum computing, classical cryptographic systems are becoming increasingly vulnerable. This paper introduces a novel lattice-based cryptographic algorithm designed to be resistant to attacks from both classical and quantum computers...',
        categories: ['cs.CR', 'quant-ph'],
        url: 'https://arxiv.org/abs/2307.01234',
        source: 'research',
    },
    {
        id: '8',
        title: 'System and Method for Semantic Analysis of Legal Contracts',
        authors: 'InnovateLegal Corp',
        date: 'May. 2022',
        abstract: 'A patented system utilizing Natural Language Processing (NLP) models to automatically review and identify key clauses, risks, and obligations within legal contracts. The system provides a summarized analysis, reducing manual review time for legal professionals.',
        categories: ['cs.CL', 'cs.AI'],
        url: 'https://patents.google.com/patent/US11234567B2',
        source: 'patent',
    },
    {
        id: '9',
        title: 'Generative Adversarial Networks for Photorealistic Image Synthesis',
        authors: 'J. Rodriguez, A. Kim',
        date: 'Mar. 2021',
        abstract: 'We present a new architecture for Generative Adversarial Networks (GANs) that achieves state-of-the-art results in photorealistic image synthesis. Our key innovation is a style-based generator that allows for intuitive, scale-specific control over the synthesis process...',
        categories: ['cs.CV', 'cs.LG'],
        url: 'https://arxiv.org/abs/2103.05678',
        source: 'research',
    },
    {
        id: '10',
        title: 'Deep Reinforcement Learning for Autonomous Drone Navigation in Complex Environments',
        authors: 'F. Ivanova, T. Williams',
        date: 'Oct. 2022',
        abstract: 'This paper presents a deep reinforcement learning framework that enables autonomous drones to navigate cluttered and unknown environments. Using only onboard sensors, our agent learns a robust policy for obstacle avoidance and goal-reaching, outperforming traditional path-planning algorithms.',
        categories: ['cs.RO', 'cs.AI'],
        url: 'https://arxiv.org/abs/2210.09876',
        source: 'research',
    },
    {
        id: '11',
        title: 'Automated Medical Imaging Analysis System',
        authors: 'MediAI Innovations',
        date: 'Feb. 2024',
        abstract: 'A patented system for the automated analysis of medical images, such as MRIs and CT scans. The system employs a convolutional neural network to detect and classify anomalies, assisting radiologists in making faster and more accurate diagnoses.',
        categories: ['cs.CV', 'cs.AI', 'med-ph'],
        url: 'https://patents.google.com/patent/US11987654B2',
        source: 'patent',
    },
];